name: Publish docs

on:
  workflow_dispatch:

jobs:
  documentation:
    name: Documentation with Paradox
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xms2G -Xmx2G -Xss2M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Install sbt
        uses: sbt/setup-sbt@v1

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6

      - name: "Create site with Paradox"
        run: cd docs && sbt makeSite

      # Create directory structure upfront since rsync does not create intermediate directories otherwise
      - name: Create doc directory structure
        run: |-
          mkdir -p target/nightly-docs/docs/pekko-connectors-samples/${{ github.ref_name }}-snapshot/
          mv docs/target/site/ target/nightly-docs/docs/pekko-connectors-samples/${{ github.ref_name }}-snapshot/docs

      - name: Upload nightly docs
        uses: ./.github/actions/sync-nightlies
        with:
          upload: true
          switches: --archive --compress --update --delete --progress --relative
          local_path: target/nightly-docs/./docs/pekko-connectors-samples/${{ github.ref_name }}-snapshot # The intermediate dot is to show `--relative` which paths to operate on
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/pekko/
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}